# SPDX-FileCopyrightText: 2026 H2Lab Development Team
#
# SPDX-License-Identifier: Apache-2.0

[build-system]
requires = ["setuptools>=80", "setuptools_scm>=9"]
build-backend = "setuptools.build_meta"

[project]
name = "pyGdbToolkit"
description = "A complete toolkit for gdb-based audit and debugging"
dynamic = ["version"]
requires-python = ">= 3.12"
readme = "README.md"
authors = [
  {name = "Florent Valette"},
  {name = "Philippe Thierry"},
]
license = {file = "LICENSES/Apache-2.0.txt"}
dependencies = [
    "rich>=13.6",
]
classifiers = [
    "Development Status :: 4 - Beta",

    "Intended Audience :: Developers",

    "Topic :: Software Development :: Debuggers",

    "License :: OSI Approved :: Apache Software License",

    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]

[project.urls]
Homepage = "https://github.com/h2lab"
# Documentation = TODO
Repository = "https://github.com/h2lab/pyGdbToolkit"
Issues = "https://github.com/h2lab/pyGdbToolkit/issues"

[project.optional-dependencies]
dev = [
    "black",
    "flake8",
    "flake8-docstrings",
    "mypy",
    "pytest",
    "tox",
]

[tool.setuptools_scm]

[tool.black]
line-length = 100
target-version = ["py312"]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.mypy]
python_version = "3.12"
strict = true
files = ["src"]
