# Copy to /etc/pygdbserver/<USB-serial>.conf and edit for this probe.
PYGDBSERVER_CONFIG=/etc/pygdbserver/servercfg-multi.json
DEVICE_PATH=/dev/serial/by-id/usb-STMicroelectronics_STLINK-V3_004300483232510239353236-if02
LISTEN_ADDRESS=0.0.0.0:1234
